twig:
    globals:
        site_name: "%app.site_name%"
        google_recaptcha: '%env(GOOGLE_RECATCHA_SITE_KEY)%'
    form_themes: ['bootstrap_5_layout.html.twig']
    default_path: '%kernel.project_dir%/templates'

when@test:
    twig:
        strict_variables: true
